{{/*apiVersion: apps/v1*/}}
{{/*kind: Deployment*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Release.Name }}-{{ .Values.openldap.service.name }}*/}}
{{/*  labels:*/}}
{{/*    {{ include "flowable.defaultlabels" . }}*/}}
{{/*spec:*/}}
{{/*  replicas: {{ .Values.openldap.replicas }}*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      app.kubernetes.io/name: {{ .Release.Name }}-{{ include "flowable.template" . }}*/}}
{{/*      app.kubernetes.io/instance: {{ .Release.Name }}*/}}
{{/*  template:*/}}
{{/*    metadata:*/}}
{{/*      labels:*/}}
{{/*        app.kubernetes.io/name: {{ .Release.Name }}-{{ include "flowable.template" . }}*/}}
{{/*        app.kubernetes.io/instance: {{ .Release.Name }}*/}}
{{/*        type: {{ .Release.Name }}-openldap*/}}
{{/*      annotations:*/}}
{{/*    spec:*/}}
{{/*      imagePullSecrets:*/}}
{{/*        {{- $imageSecretNamePrefix := default .Release.Name .Values.flowable.release }}*/}}
{{/*        - name: {{ $imageSecretNamePrefix }}-{{ .Values.openldap.image.secret}}*/}}
{{/*      volumes:*/}}
{{/*        - name: openldap-ldap-data*/}}
{{/*          persistentVolumeClaim:*/}}
{{/*            claimName: {{ .Release.Name }}-{{ include "flowable.template" . }}-openldap-ldap-storage*/}}
{{/*        - name: openldap-sldapd-data*/}}
{{/*          persistentVolumeClaim:*/}}
{{/*            claimName: {{ .Release.Name }}-{{ include "flowable.template" . }}-openldap-sldapd-storage*/}}
{{/*      containers:*/}}
{{/*        - name: {{ .Release.Name }}-{{ include "flowable.template" . }}*/}}
{{/*          image: "{{ .Values.openldap.image.repository }}:{{ .Values.openldap.image.tag }}"*/}}
{{/*          {{- if .Values.openldap.image.pullPolicy }}*/}}
{{/*          imagePullPolicy: {{ .Values.openldap.image.pullPolicy }}*/}}
{{/*          {{- end }}*/}}
{{/*          resources:*/}}
{{/*{{ toYaml .Values.openldap.resources | indent 12 }}*/}}
{{/*          ports:*/}}
{{/*            - containerPort: 389*/}}
{{/*          volumeMounts:*/}}
{{/*            - mountPath: /var/lib/ldap*/}}
{{/*              name: openldap-ldap-data*/}}
{{/*            - mountPath: /etc/ldap/slapd.d*/}}
{{/*              name: openldap-sldapd-data*/}}
{{/*          env:*/}}
{{/*            - name: LDAP_ORGANISATION*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: openldap-config*/}}
{{/*                  key: ldap_organisation*/}}
{{/*            - name: LDAP_DOMAIN*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: openldap-config*/}}
{{/*                  key: ldap_domain*/}}
{{/*            - name: LDAP_ADMIN_PASSWORD*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  name: openldap-secret*/}}
{{/*                  key: ldap_admin_password*/}}
{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Release.Name }}-{{ .Values.openldap.service.name }}*/}}
{{/*  labels:*/}}
{{/*    {{ include "flowable.defaultlabels" . }}*/}}
{{/*spec:*/}}
{{/*  clusterIP: None*/}}
{{/*  selector:*/}}
{{/*    app.kubernetes.io/name: {{ .Release.Name }}-{{ include "flowable.template" . }}*/}}
{{/*    app.kubernetes.io/instance: {{ .Release.Name }}*/}}
{{/*  ports:*/}}
{{/*    - name: ldap*/}}
{{/*      protocol: TCP*/}}
{{/*      port: 389*/}}
{{/*      targetPort: 389*/}}
{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: ConfigMap*/}}
{{/*metadata:*/}}
{{/*  name: openldap-config*/}}
{{/*data:*/}}
{{/*  ldap_organisation: "{{ .Values.openldap.service.organization }}"*/}}
{{/*  ldap_domain: "{{ .Values.openldap.service.domain }}"*/}}
{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: PersistentVolumeClaim*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Release.Name }}-{{ include "flowable.template" . }}-openldap-ldap-storage*/}}
{{/*  annotations:*/}}
{{/*    volume.beta.kubernetes.io/storage-provisioner: {{ .Values.openldap.storage.provisioner }}*/}}
{{/*    helm.sh/resource-policy: "keep"*/}}
{{/*spec:*/}}
{{/*  accessModes:*/}}
{{/*    - {{ .Values.openldap.storage.accessModes }}*/}}
{{/*  storageClassName: {{ .Values.openldap.storage.storageClass }}*/}}
{{/*  resources:*/}}
{{/*    requests:*/}}
{{/*      storage: {{ .Values.openldap.storage.size }}*/}}
{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: PersistentVolumeClaim*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Release.Name }}-{{ include "flowable.template" . }}-openldap-sldapd-storage*/}}
{{/*  annotations:*/}}
{{/*    volume.beta.kubernetes.io/storage-provisioner: {{ .Values.openldap.storage.provisioner }}*/}}
{{/*    helm.sh/resource-policy: "keep"*/}}
{{/*spec:*/}}
{{/*  accessModes:*/}}
{{/*    - {{ .Values.openldap.storage.accessModes }}*/}}
{{/*  storageClassName: {{ .Values.openldap.storage.storageClass }}*/}}
{{/*  resources:*/}}
{{/*    requests:*/}}
{{/*      storage: {{ .Values.openldap.storage.size }}*/}}
{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: Secret*/}}
{{/*metadata:*/}}
{{/*  name: openldap-secret*/}}
{{/*type: Opaque*/}}
{{/*stringData:*/}}
{{/*  ldap_admin_password: "{{ .Values.openldap.service.adminPassword }}"*/}}
